package com.znty.sirm.model;

import lombok.Data;
import java.math.BigDecimal;

/**
 * 债券信息业务对象，对应 sirm_bondinfo 表
 */
@Data
public class BondInfoBo {
    /** 主键 ID */
    private Long id;
    /** 关联代码代码（债券代码） */
    private String sInfoCode;
    /** 债券全称 */
    private String bInfoFullname;
    /** 公告日期 */
    private String bIssueAnnouncement;
    /** 债券简称 */
    private String sInfoName;
    /** 沪市债券代码 */
    private String sWindcodeSh;
    /** 深市债券代码 */
    private String sWindcodeSz;
    /** 银行间市场代码 */
    private String sWindcodeNib;
    /** 其他市场代码 */
    private String sWindcodeNbc;
    /** 债券类型（1=中期票据 2=公司债 3=可交换债 4=商业银行债 5=短期融资券 6=资产支持证券 7=超短期融资券） */
    private Integer dBondType;
    /** 债券期限(年) */
    private BigDecimal bInfoTermYear;
    /** 债券期限(天) */
    private BigDecimal bInfoTermDay;
    /** 债券形式 */
    private String bInfoForm;
    /** 品种类别 */
    private String sInfoSectypename;
    /** 发行人类型 */
    private String sInfoComptype;
    /** 发行人 */
    private String bInfoIssuer;
    /** 发行人代码 */
    private String bInfoIssuercode;
    /** 币种 */
    private String crncyCode;
    /** 发行规模(亿元) */
    private BigDecimal bIssueAmountplan;
    /** 上市日期 */
    private String bInfoListdate;
    /** 发行日期 */
    private String bIssueFirstissue;
    /** 到期日期 */
    private String bInfoMaturitydate;
    /** 起息日期 */
    private String bInfoCarrydate;
    /** 止息日期 */
    private String bInfoEnddate;
    /** 利率类型 */
    private String bInfoInteresttype;
    /** 付息方式 */
    private String bInfoInterestfrequency;
    /** 每年付息次数 */
    private Integer bInfoInterestyearcount;
    /** 票面利率(%) */
    private String bInfoCouponrate;
    /** 基本利差(%) */
    private String bInfoSpread;
    /** 是否可赎回 */
    private String bInfoRedemptionflag;
    /** 赎回日期 */
    private String bInfoRedemptiondate;
    /** 赎回价格 */
    private BigDecimal bInfoRedemptionprice;
    /** 可回售性 */
    private String bInfoRepurchaseflag;
    /** 回售日期 */
    private String bInfoRepurchasedate;
    /** 回售价格 */
    private BigDecimal bInfoRepurchaseprice;
    /** 兑付起始日 */
    private String bInfoPaymentdate;
    /** 摘牌日 */
    private String bInfoDelistdate;
    /** 短期融资券利率说明 */
    private String bInfoRedemptioncontent;
    /** 赎回条款 */
    private String bInfoIssuetype;
    /** 发行方式 */
    private String bInfoCallbkorputbkdate;
    /** 行权日 */
    private String bInfoContent;
    /** 是否公司债 */
    private Integer isCorporateBond;
    /** 是否可提前兑付 */
    private String isPayadvanced;
    /** 是否可赎回 */
    private String isCallable;
    /** 是否有选择权 */
    private String isChooseright;
    /** 是否增发债 */
    private String isIncbonds;
    /** 一级板块 */
    private String sInfoIndustryname;
    /** 二级板块 */
    private String sInfoIndustryname2;
    /** 内部分类 */
    private String sInfoInnerclass;
    /** 是否次级 */
    private String isCj;
    /** 是否永续 */
    private String isYx;
    /** 是否递延 */
    private String isDy;
    /** 是否递延（重复字段） */
    private String isDeferred;
    /** 债券期限(文本形式) */
    private String bInfoTermStr;
    /** 主承销商 */
    private String bInfoLeadUnderwriter;
    /** 当期利率(%) */
    private BigDecimal bInfoCurInterestrate;
    /** 质押比率(%) */
    private BigDecimal bInfoPledgeRatio;
    /** 担保情况 */
    private String bInfoGuaranteeStatus;
    /** 行权剩余期限 */
    private String bInfoRemExeTerm;
    /** 回售行权期限 */
    private String bInfoPutExeTerm;
    /** 赎回行权剩余期限 */
    private String bInfoCallRemTerm;
    /** 含权债剩余期限 */
    private String bInfoOptRemTerm;
    /** 评级机构 */
    private String creditRatingAgency;
    /** 债券评级 */
    private String bCreditRating;
    /** 主体评级 */
    private String issuerCreditRating;
    /** 展望评级 */
    private String ratingOutlook;
    /** 主体内评分档 */
    private String innerIssuerRating;
    /** 担保人主体内评分 */
    private String innerGuarantorRating;
    /** 募集资金用途 */
    private String bFundUsage;
    /** 提示原因 */
    private String bPromptReason;
    /** 债券分析 */
    private String bAnalysis;
}
