package com.znty.sirm.model;

import lombok.Data;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 证券信息业务对象，对应 sirm_securityinfo 表
 */
@Data
public class SecurityInfoBo {
    /** 主键 ID */
    private Long id;
    /** 关联代码 */
    private String windCode;
    /** 证券全称 */
    private String fullName;
    /** 公告日期 */
    private String issueAnnouncement;
    /** 证券简称 */
    private String infoName;
    /** 沪市证券代码 */
    private String windCodeSh;
    /** 深市证券代码 */
    private String windCodeSz;
    /** 银行间市场代码 */
    private String windCodeNib;
    /** 北交所代码 */
    private String windCodeBj;
    /** 其他 */
    private String windCodeNbc;
    /** 证券类型编码 */
    private String securityType;
    /** 证券期限(年) */
    private BigDecimal infoTermYear;
    /** 证券期限(天) */
    private BigDecimal infoTermDay;
    /** 证券形式 */
    private String infoForm;
    /** 品种类别 */
    private String infoSectypename;
    /** 发行人类型 */
    private String infoComptype;
    /** 发行人 */
    private String infoIssuer;
    /** 发行人代码 */
    private String infoIssuercode;
    /** 币种 */
    private String crncyCode;
    /** 发行规模(亿元) */
    private BigDecimal issueAmountplan;
    /** 上市日期 */
    private String infoListdate;
    /** 发行日期 */
    private String issueFirstissue;
    /** 到期日期 */
    private String infoMaturitydate;
    /** 起息日期 */
    private String infoCarrydate;
    /** 止息日期 */
    private String infoEnddate;
    /** 利率类型 */
    private String infoInteresttype;
    /** 付息方式 */
    private String infoInterestfrequency;
    /** 每年付息次数 */
    private Integer infoInterestyearcount;
    /** 票面利率(%) */
    private String infoCouponrate;
    /** 基本利差(%) */
    private String infoSpread;
    /** 是否可赎回 */
    private String isRedemption;
    /** 赎回日期 */
    private String infoRedemptiondate;
    /** 赎回价格 */
    private BigDecimal infoRedemptionprice;
    /** 可回售性 */
    private String isRepurchase;
    /** 回售日期 */
    private String infoRepurchasedate;
    /** 回售价格 */
    private BigDecimal infoRepurchaseprice;
    /** 兑付起始日 */
    private String infoPaymentdate;
    /** 摘牌日 */
    private String infoDelistdate;
    /** 短期融资券,如果F4_1090等于DQ时-1,否则为0 */
    private Integer infoSecuritiestypesDq;
    /** 利率说明 */
    private String infoCoupontxt;
    /** 赎回条款 */
    private String infoRedemptioncontent;
    /** 发行方式 */
    private String infoIssuetype;
    /** 行权日 */
    private String infoCallbkorputbkdate;
    /** 赎回条款 */
    private String infoContent;
    /** 创建时间 */
    private Date createtime;
    /** 更新时间 */
    private Date ts;
    /** 是否公司证券 */
    private Integer isCorporateSecurity;
    /** 是否可提前兑付 */
    private String isPayadvanced;
    /** 是否可赎回 */
    private String isCallable;
    /** 是否有选择权 */
    private String isChooseright;
    /** 是否增发证券 */
    private String isIncsecurities;
    /** 一级板块 */
    private String infoIndustryname;
    /** 二级板块 */
    private String infoIndustryname2;
    /** 内部分类 */
    private String infoInnerclass;
    /** 是否次级 */
    private String isCj;
    /** 是否永续 */
    private String isYx;
    /** 是否递延 */
    private String isDy;
    /** 回售剩余期限-最新 */
    private String dateRedemtionExists;
    /** 赎回剩余期限-最新 */
    private String dateCallExists;
    /** 证券期限-最新 */
    private String dateExists;
    /** 含权证券剩余期限-最新 */
    private String dateInrightExists;
    /** 证券评级 */
    private String ratingSecurity;
    /** 主体评级 */
    private String ratingSecurityissuer;
    /** 展望评级 */
    private String ratingOutlook;
    /** 证券评级机构 */
    private String ratingSecurityAgency;
    /** 主体评级机构 */
    private String ratingSecurityissuerAgency;
    /** 中债隐含评级 */
    private String ratingCnbd;
    /** 是否含权证券 */
    private String isInright;
    /** 含权证券下一个行权日 */
    private String dateInrightNext;
    /** 发行总额-亿 */
    private BigDecimal issueAmountact;
    /** 担保方式 */
    private String agencyGrnttype;
    /** 担保人 */
    private String guarantor;
    /** 担保人ID */
    private String guarantorId;
    /** 主承销商 */
    private String agencyName;
    /** 主承销商Id */
    private String agencyNameid;
    /** 质押比率(%) */
    private BigDecimal infoPledgeRatio;
    /** 主体内评分档 */
    private String innerIssuerRating;
    /** 担保人主体内评分 */
    private String innerGuarantorRating;
    /** 募集资金用途 */
    private String fundUsage;
    /** 提示原因 */
    private String promptReason;
    /** 证券分析 */
    private String analysis;
}
