-- ============================================================
-- znty-rrs 投资池初始化 - 演示数据脚本
-- MySQL version: 8.0.28
-- 说明：首次部署执行，插入投资池相关测试数据
-- ============================================================

CREATE DATABASE IF NOT EXISTS `znty_rrs` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `znty_rrs`;
SET NAMES utf8mb4;

-- ----------------------------------------------------------------------------
-- 清空所有业务表
-- ----------------------------------------------------------------------------
TRUNCATE TABLE `ip_pool_permission_evt`;
TRUNCATE TABLE `ip_pool_auto_rule_evt`;
TRUNCATE TABLE `ip_pool_relation_evt`;
TRUNCATE TABLE `ip_investment_pool_evt`;
TRUNCATE TABLE `ip_pool_permission`;
TRUNCATE TABLE `ip_pool_auto_rule`;
TRUNCATE TABLE `ip_pool_relation`;
TRUNCATE TABLE `ip_investment_pool`;

-- 投资池（94 池）
-- 审批流程说明：简易入/出=快速入/出库(105/106)；批量入/出=批量入/出库(107/108)；研报限制默认 none
-- 特例：观察池(16)/黑名单质押库(17)/CRMW库(18)/重点观察名单(23) 的 6 个调入调出流程均绑「无需审核审批流程」(112 / bond:no-approval)
-- 展示顺序 outer_sort（对齐老系统截图）：
--   1=信用债大库(new)  2=转债库  3=境外债  4=债券产品库  5=兴业中高等级信用债
--   6=白名单库  7=黑名单质押库  8=债券禁止库  9=CRMW库  10=债券产品库1
--   11=观察池  12=重点观察名单  13=交易对手额度统计债券库  14=信用债大库(old)
-- 风险名单：15=债券禁止库 / 16=观察池 / 17=黑名单质押库 / 23=重点观察名单 / 64=白名单库
-- 境外债：7 + 24～28；转债：8 + 29～31
-- 债券产品库：32～57；兴业中高等级：58～63；债券产品库1：65～85
-- 交易对手额度：86 + 87～98（一至十二级）；信用债大库(old)：99 + 100～104
-- 已移除：专户产品、基金池；CRMW 仅保留根池（无子集）；禁止库展示名为债券禁止库
INSERT INTO `ip_investment_pool` (
    `id`, `parent_id`, `pool_code`, `pool_name`, `pool_type`, `pool_level`,
    `market_codes`, `variety_codes`, `description`, `hs_pool_name`,
    `in_flow_id`, `in_flow_key`, `in_flow_name`,
    `out_flow_id`, `out_flow_key`, `out_flow_name`,
    `simple_in_flow_id`, `simple_in_flow_key`, `simple_in_flow_name`,
    `simple_out_flow_id`, `simple_out_flow_key`, `simple_out_flow_name`,
    `batch_in_flow_id`, `batch_in_flow_key`, `batch_in_flow_name`,
    `batch_out_flow_id`, `batch_out_flow_key`, `batch_out_flow_name`,
    `in_report_restriction`, `out_report_restriction`,
    `max_capacity`, `lock_flag`, `frozen_period_in`, `grade_astrict`,
    `industry_code`, `industry_exponent`, `fund_rate_limit`, `open_day_adjust`,
    `outer_sort`, `inner_sort`, `status`, `is_deleted`, `crte_time`, `updt_time`
) VALUES
(1, NULL, 'credit_bond_root', '信用债大库(new)', 'credit_bond', 1, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '信用债大库(new)根池', NULL, 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 1, 1, 'enabled', 0, NOW(), NOW()),
(2, 1, 'credit_bond_level_1', '一级库', 'credit_bond', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '信用债一级库', '公司债券一级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 1, 1, 'enabled', 0, NOW(), NOW()),
(3, 1, 'credit_bond_level_2', '二级库', 'credit_bond', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '信用债二级库', '公司债券二级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 1, 2, 'enabled', 0, NOW(), NOW()),
(4, 1, 'credit_bond_level_3', '三级库', 'credit_bond', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '信用债三级库', '公司债券三级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 1, 3, 'enabled', 0, NOW(), NOW()),
(5, 1, 'credit_bond_level_4', '四级库', 'credit_bond', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '信用债四级库', '公司债券四级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 1, 4, 'enabled', 0, NOW(), NOW()),
(6, 1, 'credit_bond_level_5', '五级库', 'credit_bond', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '信用债五级库', '公司债券五级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, '制造业', 0, NULL, 0, 1, 5, 'enabled', 0, NOW(), NOW()),
(7, NULL, 'offshore_bond_root', '境外债', 'offshore_bond', 1, '["JWCW"]', '["bond"]', '境外债根池', NULL, 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 3, 1, 'enabled', 0, NOW(), NOW()),
(8, NULL, 'convertible_bond_root', '转债库', 'convertible_bond', 1, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '转债库根池', NULL, 109, 'bond:special-inbound', '债券特殊策略入库流程', 110, 'bond:special-outbound', '债券特殊策略出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 1, 2, 1, 'enabled', 0, NOW(), NOW()),
(15, NULL, 'forbidden_root', '债券禁止库', 'forbidden', 1, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '债券禁止库', '债券禁止库新', 113, 'company:forbidden-inbound', '禁止库入库流程', 114, 'company:forbidden-outbound', '禁止库出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 8, 1, 'enabled', 0, NOW(), NOW()),
(16, NULL, 'observe_root', '观察池', 'observe', 1, '["SSE","SZSE","CIBM","COMPANY","OTC"]', '["bond","company"]', '观察池', NULL, 112, 'bond:no-approval', '无需审核审批流程', 112, 'bond:no-approval', '无需审核审批流程', 112, 'bond:no-approval', '无需审核审批流程', 112, 'bond:no-approval', '无需审核审批流程', 112, 'bond:no-approval', '无需审核审批流程', 112, 'bond:no-approval', '无需审核审批流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 11, 1, 'enabled', 0, NOW(), NOW()),
(17, NULL, 'pledge_blacklist_root', '黑名单质押库', 'blacklist', 1, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '黑名单质押库', '黑名单质押库', 112, 'bond:no-approval', '无需审核审批流程', 112, 'bond:no-approval', '无需审核审批流程', 112, 'bond:no-approval', '无需审核审批流程', 112, 'bond:no-approval', '无需审核审批流程', 112, 'bond:no-approval', '无需审核审批流程', 112, 'bond:no-approval', '无需审核审批流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 7, 1, 'enabled', 0, NOW(), NOW()),
(18, NULL, 'crmw_root', 'CRMW库', 'crmw', 1, '["UNKNOWN","SSE","SZSE","CIBM","OTC"]', '["bond"]', 'CRMW库', 'CRMW大库', 112, 'bond:no-approval', '无需审核审批流程', 112, 'bond:no-approval', '无需审核审批流程', 112, 'bond:no-approval', '无需审核审批流程', 112, 'bond:no-approval', '无需审核审批流程', 112, 'bond:no-approval', '无需审核审批流程', 112, 'bond:no-approval', '无需审核审批流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 9, 1, 'enabled', 0, NOW(), NOW()),
(23, NULL, 'key_watch_list_root', '重点观察名单', 'restricted', 1, '["SSE","SZSE","CIBM","COMPANY","OTC"]', '["bond","company"]', '重点观察名单', NULL, 112, 'bond:no-approval', '无需审核审批流程', 112, 'bond:no-approval', '无需审核审批流程', 112, 'bond:no-approval', '无需审核审批流程', 112, 'bond:no-approval', '无需审核审批流程', 112, 'bond:no-approval', '无需审核审批流程', 112, 'bond:no-approval', '无需审核审批流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 12, 1, 'enabled', 0, NOW(), NOW()),
(24, 7, 'offshore_bond_level_1', '境外债一级库', 'offshore_bond', 2, '["JWCW"]', '["bond"]', '境外债一级库', NULL, 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 3, 1, 'enabled', 0, NOW(), NOW()),
(25, 7, 'offshore_bond_level_2', '境外债二级库', 'offshore_bond', 2, '["JWCW"]', '["bond"]', '境外债二级库', NULL, 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 3, 2, 'enabled', 0, NOW(), NOW()),
(26, 7, 'offshore_bond_level_3', '境外债三级库', 'offshore_bond', 2, '["JWCW"]', '["bond"]', '境外债三级库', NULL, 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 3, 3, 'enabled', 0, NOW(), NOW()),
(27, 7, 'offshore_bond_level_4', '境外债四级库', 'offshore_bond', 2, '["JWCW"]', '["bond"]', '境外债四级库', NULL, 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 3, 4, 'enabled', 0, NOW(), NOW()),
(28, 7, 'offshore_bond_level_5', '境外债五级库', 'offshore_bond', 2, '["JWCW"]', '["bond"]', '境外债五级库', NULL, 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 3, 5, 'enabled', 0, NOW(), NOW()),
(29, 8, 'convertible_bond_core', '核心库', 'convertible_bond', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '转债核心库', '转债核心库', 109, 'bond:special-inbound', '债券特殊策略入库流程', 110, 'bond:special-outbound', '债券特殊策略出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 2, 1, 'enabled', 0, NOW(), NOW()),
(30, 8, 'convertible_bond_focus', '重点库', 'convertible_bond', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '转债重点库', '转债重点库', 109, 'bond:special-inbound', '债券特殊策略入库流程', 110, 'bond:special-outbound', '债券特殊策略出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 2, 2, 'enabled', 0, NOW(), NOW()),
(31, 8, 'convertible_bond_basic', '基础库', 'convertible_bond', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '转债基础库', '转债基础库', 109, 'bond:special-inbound', '债券特殊策略入库流程', 110, 'bond:special-outbound', '债券特殊策略出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 2, 3, 'enabled', 0, NOW(), NOW()),
(32, NULL, 'bond_product_root', '债券产品库', 'bond_product', 1, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '债券产品库根池', NULL, 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 1, 'enabled', 0, NOW(), NOW()),
(33, 32, 'bond_product_wenfu_1', '稳富1号', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '稳富1号', '稳富1号信用债一级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 1, 'enabled', 0, NOW(), NOW()),
(34, 32, 'bond_product_jiaxing_bank_1', '嘉兴银行1号', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '嘉兴银行1号', '嘉兴银行1号一级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 2, 'enabled', 0, NOW(), NOW()),
(35, 32, 'bond_product_wenfu_12', '稳富12号', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '稳富12号', '稳富12号信用债一级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 3, 'enabled', 0, NOW(), NOW()),
(36, 32, 'bond_product_wenfu_13', '稳富13号', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '稳富13号', '稳富13号信用债一级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 4, 'enabled', 0, NOW(), NOW()),
(37, 32, 'bond_product_wenfu_14', '稳富14号', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '稳富14号', '稳富14号信用债一级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 5, 'enabled', 0, NOW(), NOW()),
(38, 32, 'bond_product_wenfu_20', '稳富20号', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '稳富20号', '稳富20号信用债一级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 6, 'enabled', 0, NOW(), NOW()),
(39, 32, 'bond_product_wenfu_29', '稳富29号', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '稳富29号', '稳富29号信用债一级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 7, 'enabled', 0, NOW(), NOW()),
(40, 32, 'bond_product_wenfu_58', '稳富58号', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '稳富58号', '稳富58号信用债一级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 8, 'enabled', 0, NOW(), NOW()),
(41, 32, 'bond_product_xingjin_490', '兴金490号', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '兴金490号', '兴金490一级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 9, 'enabled', 0, NOW(), NOW()),
(42, 32, 'bond_product_xingrui_5', '兴锐5号', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '兴锐5号', '兴锐5号债券库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 10, 'enabled', 0, NOW(), NOW()),
(43, 32, 'bond_product_zijin_1_1', '紫金1号1期', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '紫金1号1期', '紫金1号1期大库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 11, 'enabled', 0, NOW(), NOW()),
(44, 32, 'bond_product_xingye_jingtong', '兴业京通', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '兴业京通', '京通大库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 12, 'enabled', 0, NOW(), NOW()),
(45, 32, 'bond_product_xingye_taibao', '兴业太保大库', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '兴业太保大库', '兴业太保大库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 13, 'enabled', 0, NOW(), NOW()),
(46, 32, 'bond_product_zijin_1_2', '紫金1号2期', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '紫金1号2期', '紫金1号2期大库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 14, 'enabled', 0, NOW(), NOW()),
(47, 32, 'bond_product_xingfu_101', '兴富101号', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '兴富101号', '兴富101号大库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 15, 'enabled', 0, NOW(), NOW()),
(48, 32, 'bond_product_xingye_jinghua', '兴业京华债券大库', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '兴业京华债券大库', '兴业京华债券大库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 16, 'enabled', 0, NOW(), NOW()),
(49, 32, 'bond_product_xingye_wenying', '兴业稳盈', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '兴业稳盈', '兴业稳盈大库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 17, 'enabled', 0, NOW(), NOW()),
(50, 32, 'bond_product_zijin_1_3', '紫金1号3期', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '紫金1号3期', '紫金1号3期大库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 18, 'enabled', 0, NOW(), NOW()),
(51, 32, 'bond_product_zijin_1_4', '紫金1号4期', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '紫金1号4期', '紫金1号4期大库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 19, 'enabled', 0, NOW(), NOW()),
(52, 32, 'bond_product_kunlun_1', '昆仑1号', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '昆仑1号', '昆仑1号大库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 20, 'enabled', 0, NOW(), NOW()),
(53, 32, 'bond_product_xingye_green', '兴业绿色信用债库', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '兴业绿色信用债库', '兴业绿色信用债库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 21, 'enabled', 0, NOW(), NOW()),
(54, 32, 'bond_product_zengli_chanye', '增利产业债认定', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '增利产业债认定', '增利产业债认定', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 22, 'enabled', 0, NOW(), NOW()),
(55, 32, 'bond_product_wenrui_888', '稳睿888号', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '稳睿888号', '稳睿888', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 23, 'enabled', 0, NOW(), NOW()),
(56, 32, 'bond_product_wenrui_8881', '稳睿8881号', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '稳睿8881号', '稳睿8881', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 24, 'enabled', 0, NOW(), NOW()),
(57, 32, 'bond_product_xingfu_99', '兴富99号', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '兴富99号', '兴富99号大库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 4, 25, 'enabled', 0, NOW(), NOW()),
(58, NULL, 'xy_mid_high_credit_root', '兴业中高等级信用债', 'credit_bond', 1, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '兴业中高等级信用债', NULL, 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 5, 1, 'enabled', 0, NOW(), NOW()),
(59, 58, 'xy_mid_high_credit_l1', '一级库', 'credit_bond', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '兴业中高等级信用债一级库', '中证兴业中高等级信用债指数一级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 5, 1, 'enabled', 0, NOW(), NOW()),
(60, 58, 'xy_mid_high_credit_l2', '二级库', 'credit_bond', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '兴业中高等级信用债二级库', '中证兴业中高等级信用债指数二级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 5, 2, 'enabled', 0, NOW(), NOW()),
(61, 58, 'xy_mid_high_credit_l3', '三级库', 'credit_bond', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '兴业中高等级信用债三级库', '中证兴业中高等级信用债指数三级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 5, 3, 'enabled', 0, NOW(), NOW()),
(62, 58, 'xy_mid_high_credit_l4', '四级库', 'credit_bond', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '兴业中高等级信用债四级库', '中证兴业中高等级信用债指数四级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 5, 4, 'enabled', 0, NOW(), NOW()),
(63, 58, 'xy_mid_high_credit_restricted', '流通受限库', 'credit_bond', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '兴业中高等级信用债流通受限库', '中证指数流通受限库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 5, 5, 'enabled', 0, NOW(), NOW()),
(64, NULL, 'whitelist_root', '白名单库', 'whitelist', 1, '["SSE","SZSE","CIBM","OTC"]', '["company"]', '白名单库', NULL, 106, 'bond:whitelist-inbound', '债券白名单入库流程', 112, 'bond:no-approval', '无需审核审批流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 6, 1, 'enabled', 0, NOW(), NOW()),
(65, NULL, 'bond_product1_root', '债券产品库1', 'bond_product', 1, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '债券产品库1', '债券产品库1', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 10, 1, 'enabled', 0, NOW(), NOW()),
(66, 65, 'bond_product1_xy_currency', '兴业货币名单', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '兴业货币名单', '兴业货币名单', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 10, 1, 'enabled', 0, NOW(), NOW()),
(67, 66, 'bond_product1_xy_abs', 'ABS名单', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', 'ABS名单', 'ABS名单', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 10, 1, 'enabled', 0, NOW(), NOW()),
(68, 66, 'bond_product1_xy_credit_5', '信用5%名单', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '信用5%名单', '信用5%名单', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 10, 2, 'enabled', 0, NOW(), NOW()),
(69, 66, 'bond_product1_xy_credit_3_5', '信用3.5%名单', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '信用3.5%名单', '信用3.5%名单', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 10, 3, 'enabled', 0, NOW(), NOW()),
(70, 66, 'bond_product1_xy_jt', '货币JT名单', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '货币JT名单', '货币JT名单', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 10, 4, 'enabled', 0, NOW(), NOW()),
(71, 66, 'bond_product1_xy_jy', '货币JY名单', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '货币JY名单', '货币JY名单', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 10, 5, 'enabled', 0, NOW(), NOW()),
(72, 65, 'bond_product1_kunlun_1', '昆仑库1', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '昆仑库1', '昆仑库1', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 10, 2, 'enabled', 0, NOW(), NOW()),
(73, 65, 'bond_product1_tty_currency', '添天盈货币名单', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '添天盈货币名单', '添天盈货币名单', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 10, 3, 'enabled', 0, NOW(), NOW()),
(74, 73, 'bond_product1_tty_fund_3', '货基金3%', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '货基金3%', '货基金3%', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 10, 1, 'enabled', 0, NOW(), NOW()),
(75, 73, 'bond_product1_tty_pledge_over_3m', '货基质押超3月', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '货基质押超3月', '货基质押超3月', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 10, 2, 'enabled', 0, NOW(), NOW()),
(76, 73, 'bond_product1_tty_credit_1', '货基信用1%', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '货基信用1%', '货基信用1%', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 10, 3, 'enabled', 0, NOW(), NOW()),
(77, 73, 'bond_product1_tty_credit_5', '货基信用5%', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '货基信用5%', '货基信用5%', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 10, 4, 'enabled', 0, NOW(), NOW()),
(78, 73, 'bond_product1_tty_fund_2', '货基金2%', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '货基金2%', '货基金2%', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 10, 5, 'enabled', 0, NOW(), NOW()),
(79, 73, 'bond_product1_tty_pledge_black_s', '质押库黑名单小', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '质押库黑名单小', '质押库黑名单小', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 10, 6, 'enabled', 0, NOW(), NOW()),
(80, 73, 'bond_product1_tty_pledge_3m', '货基质押3个月', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '货基质押3个月', '货基质押3个月', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 10, 7, 'enabled', 0, NOW(), NOW()),
(81, 73, 'bond_product1_tty_fund_1', '货基金1%', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '货基金1%', '货基金1%', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 10, 8, 'enabled', 0, NOW(), NOW()),
(82, 73, 'bond_product1_tty_fund_0_3', '货基金0.3%', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '货基金0.3%', '货基金0.3%', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 10, 9, 'enabled', 0, NOW(), NOW()),
(83, 73, 'bond_product1_tty_fund_0', '货基金0%', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '货基金0%', '货基金0%', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 10, 10, 'enabled', 0, NOW(), NOW()),
(84, 73, 'bond_product1_tty_pledge_black_l', '质押库黑名单大', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '质押库黑名单大', '质押库黑名单大', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 10, 11, 'enabled', 0, NOW(), NOW()),
(85, 73, 'bond_product1_tty_credit_3', '货基信用3%', 'bond_product', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '货基信用3%', '货基信用3%', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 10, 12, 'enabled', 0, NOW(), NOW()),
(86, NULL, 'counterparty_quota_root', '交易对手额度统计债券库', 'other', 1, '["SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '交易对手额度统计债券库', '交易对手额度统计债券库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 13, 1, 'enabled', 0, NOW(), NOW()),
(87, 86, 'counterparty_quota_l1', '交易对手额度一级库', 'other', 2, '["SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '交易对手额度一级库', '交易对手额度一级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 13, 1, 'enabled', 0, NOW(), NOW()),
(88, 86, 'counterparty_quota_l2', '交易对手额度二级库', 'other', 2, '["SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '交易对手额度二级库', '交易对手额度二级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 13, 2, 'enabled', 0, NOW(), NOW()),
(89, 86, 'counterparty_quota_l3', '交易对手额度三级库', 'other', 2, '["SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '交易对手额度三级库', '交易对手额度三级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 13, 3, 'enabled', 0, NOW(), NOW()),
(90, 86, 'counterparty_quota_l4', '交易对手额度四级库', 'other', 2, '["SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '交易对手额度四级库', '交易对手额度四级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 13, 4, 'enabled', 0, NOW(), NOW()),
(91, 86, 'counterparty_quota_l5', '交易对手额度五级库', 'other', 2, '["SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '交易对手额度五级库', '交易对手额度五级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 13, 5, 'enabled', 0, NOW(), NOW()),
(92, 86, 'counterparty_quota_l6', '交易对手额度六级库', 'other', 2, '["SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '交易对手额度六级库', '交易对手额度六级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 13, 6, 'enabled', 0, NOW(), NOW()),
(93, 86, 'counterparty_quota_l7', '交易对手额度七级库', 'other', 2, '["SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '交易对手额度七级库', '交易对手额度七级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 13, 7, 'enabled', 0, NOW(), NOW()),
(94, 86, 'counterparty_quota_l8', '交易对手额度八级库', 'other', 2, '["SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '交易对手额度八级库', '交易对手额度八级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 13, 8, 'enabled', 0, NOW(), NOW()),
(95, 86, 'counterparty_quota_l9', '交易对手额度九级库', 'other', 2, '["SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '交易对手额度九级库', '交易对手额度九级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 13, 9, 'enabled', 0, NOW(), NOW()),
(96, 86, 'counterparty_quota_l10', '交易对手额度十级库', 'other', 2, '["SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '交易对手额度十级库', '交易对手额度十级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 13, 10, 'enabled', 0, NOW(), NOW()),
(97, 86, 'counterparty_quota_l11', '交易对手额度十一级库', 'other', 2, '["SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '交易对手额度十一级库', '交易对手额度十一级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 13, 11, 'enabled', 0, NOW(), NOW()),
(98, 86, 'counterparty_quota_l12', '交易对手额度十二级库', 'other', 2, '["SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '交易对手额度十二级库', '交易对手额度十二级库', 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 13, 12, 'enabled', 0, NOW(), NOW()),
(99, NULL, 'credit_bond_old_root', '信用债大库(old)', 'credit_bond', 1, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '信用债大库(old)根池', NULL, 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 14, 1, 'enabled', 0, NOW(), NOW()),
(100, 99, 'credit_bond_old_l1', '一级库', 'credit_bond', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '信用债大库(old)一级库', NULL, 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 14, 1, 'enabled', 0, NOW(), NOW()),
(101, 99, 'credit_bond_old_l2', '二级库', 'credit_bond', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '信用债大库(old)二级库', NULL, 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 14, 2, 'enabled', 0, NOW(), NOW()),
(102, 99, 'credit_bond_old_l3', '三级库', 'credit_bond', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '信用债大库(old)三级库', NULL, 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 14, 3, 'enabled', 0, NOW(), NOW()),
(103, 99, 'credit_bond_old_l4', '四级库', 'credit_bond', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '信用债大库(old)四级库', NULL, 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 14, 4, 'enabled', 0, NOW(), NOW()),
(104, 99, 'credit_bond_old_restricted', '流通受限库', 'credit_bond', 2, '["UNKNOWN","SSE","SZSE","CIBM","COMPANY"]', '["bond","company"]', '信用债大库(old)流通受限库', NULL, 103, 'bond:normal-inbound', '债券一般入库流程', 104, 'bond:normal-outbound', '债券一般出库流程', 105, 'bond:fast-inbound', '债券快速入库流程', 106, 'bond:fast-outbound', '债券快速出库流程', 107, 'bond:batch-inbound', '债券批量入库流程', 108, 'bond:batch-outbound', '债券批量出库流程', 'none', 'none', 1000, 0, 0, NULL, NULL, 0, NULL, 0, 14, 5, 'enabled', 0, NOW(), NOW());
-- 池关系（按业务规则配置，子池与根池同规则；无配置的树不写关系）
-- 信用债大库(new)：调入限制=债券禁止库/重点观察名单；子库互斥
-- 转债库：调入限制=债券禁止库/重点观察名单；子库互斥
-- 债券产品库：调入限制=债券禁止库
-- 兴业中高等级信用债：调入限制=债券禁止库；子库互斥
-- 债券禁止库：调入互斥=信用债大库(new)/转债库/境外债/债券产品库 的子集（不含父级，父级不可选）；调入/调出联动=黑名单质押库
-- 重点观察名单：调入/调出联动=黑名单质押库
-- 信用债大库(old)：调入限制=债券禁止库；子库互斥
INSERT INTO `ip_pool_relation` (`pool_id`, `relation_type`, `relation_pool_id`, `relation_pool_name`, `sort_order`, `is_deleted`, `crte_time`, `updt_time`) VALUES
(1, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(1, 'in_restrict', 23, '重点观察名单', 2, 0, NOW(), NOW()),
(2, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(2, 'in_restrict', 23, '重点观察名单', 2, 0, NOW(), NOW()),
(3, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(3, 'in_restrict', 23, '重点观察名单', 2, 0, NOW(), NOW()),
(4, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(4, 'in_restrict', 23, '重点观察名单', 2, 0, NOW(), NOW()),
(5, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(5, 'in_restrict', 23, '重点观察名单', 2, 0, NOW(), NOW()),
(6, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(6, 'in_restrict', 23, '重点观察名单', 2, 0, NOW(), NOW()),
(2, 'in_mutex', 3, '二级库', 1, 0, NOW(), NOW()),
(3, 'in_mutex', 2, '一级库', 1, 0, NOW(), NOW()),
(2, 'in_mutex', 4, '三级库', 2, 0, NOW(), NOW()),
(4, 'in_mutex', 2, '一级库', 2, 0, NOW(), NOW()),
(2, 'in_mutex', 5, '四级库', 3, 0, NOW(), NOW()),
(5, 'in_mutex', 2, '一级库', 3, 0, NOW(), NOW()),
(2, 'in_mutex', 6, '五级库', 4, 0, NOW(), NOW()),
(6, 'in_mutex', 2, '一级库', 4, 0, NOW(), NOW()),
(3, 'in_mutex', 4, '三级库', 5, 0, NOW(), NOW()),
(4, 'in_mutex', 3, '二级库', 5, 0, NOW(), NOW()),
(3, 'in_mutex', 5, '四级库', 6, 0, NOW(), NOW()),
(5, 'in_mutex', 3, '二级库', 6, 0, NOW(), NOW()),
(3, 'in_mutex', 6, '五级库', 7, 0, NOW(), NOW()),
(6, 'in_mutex', 3, '二级库', 7, 0, NOW(), NOW()),
(4, 'in_mutex', 5, '四级库', 8, 0, NOW(), NOW()),
(5, 'in_mutex', 4, '三级库', 8, 0, NOW(), NOW()),
(4, 'in_mutex', 6, '五级库', 9, 0, NOW(), NOW()),
(6, 'in_mutex', 4, '三级库', 9, 0, NOW(), NOW()),
(5, 'in_mutex', 6, '五级库', 10, 0, NOW(), NOW()),
(6, 'in_mutex', 5, '四级库', 10, 0, NOW(), NOW()),
(8, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(8, 'in_restrict', 23, '重点观察名单', 2, 0, NOW(), NOW()),
(29, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(29, 'in_restrict', 23, '重点观察名单', 2, 0, NOW(), NOW()),
(30, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(30, 'in_restrict', 23, '重点观察名单', 2, 0, NOW(), NOW()),
(31, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(31, 'in_restrict', 23, '重点观察名单', 2, 0, NOW(), NOW()),
(29, 'in_mutex', 30, '重点库', 1, 0, NOW(), NOW()),
(30, 'in_mutex', 29, '核心库', 1, 0, NOW(), NOW()),
(29, 'in_mutex', 31, '基础库', 2, 0, NOW(), NOW()),
(31, 'in_mutex', 29, '核心库', 2, 0, NOW(), NOW()),
(30, 'in_mutex', 31, '基础库', 3, 0, NOW(), NOW()),
(31, 'in_mutex', 30, '重点库', 3, 0, NOW(), NOW()),
(32, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(33, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(34, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(35, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(36, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(37, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(38, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(39, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(40, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(41, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(42, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(43, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(44, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(45, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(46, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(47, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(48, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(49, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(50, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(51, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(52, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(53, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(54, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(55, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(56, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(57, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(58, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(59, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(60, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(61, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(62, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(63, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(59, 'in_mutex', 60, '二级库', 1, 0, NOW(), NOW()),
(60, 'in_mutex', 59, '一级库', 1, 0, NOW(), NOW()),
(59, 'in_mutex', 61, '三级库', 2, 0, NOW(), NOW()),
(61, 'in_mutex', 59, '一级库', 2, 0, NOW(), NOW()),
(59, 'in_mutex', 62, '四级库', 3, 0, NOW(), NOW()),
(62, 'in_mutex', 59, '一级库', 3, 0, NOW(), NOW()),
(59, 'in_mutex', 63, '流通受限库', 4, 0, NOW(), NOW()),
(63, 'in_mutex', 59, '一级库', 4, 0, NOW(), NOW()),
(60, 'in_mutex', 61, '三级库', 5, 0, NOW(), NOW()),
(61, 'in_mutex', 60, '二级库', 5, 0, NOW(), NOW()),
(60, 'in_mutex', 62, '四级库', 6, 0, NOW(), NOW()),
(62, 'in_mutex', 60, '二级库', 6, 0, NOW(), NOW()),
(60, 'in_mutex', 63, '流通受限库', 7, 0, NOW(), NOW()),
(63, 'in_mutex', 60, '二级库', 7, 0, NOW(), NOW()),
(61, 'in_mutex', 62, '四级库', 8, 0, NOW(), NOW()),
(62, 'in_mutex', 61, '三级库', 8, 0, NOW(), NOW()),
(61, 'in_mutex', 63, '流通受限库', 9, 0, NOW(), NOW()),
(63, 'in_mutex', 61, '三级库', 9, 0, NOW(), NOW()),
(62, 'in_mutex', 63, '流通受限库', 10, 0, NOW(), NOW()),
(63, 'in_mutex', 62, '四级库', 10, 0, NOW(), NOW()),
-- 债券禁止库(15) 调入互斥：仅配置各业务树可选子集（不含父级根池）
-- 信用债大库(new) 子集
(15, 'in_mutex', 2, '一级库', 1, 0, NOW(), NOW()),
(15, 'in_mutex', 3, '二级库', 2, 0, NOW(), NOW()),
(15, 'in_mutex', 4, '三级库', 3, 0, NOW(), NOW()),
(15, 'in_mutex', 5, '四级库', 4, 0, NOW(), NOW()),
(15, 'in_mutex', 6, '五级库', 5, 0, NOW(), NOW()),
-- 转债库 子集
(15, 'in_mutex', 29, '核心库', 6, 0, NOW(), NOW()),
(15, 'in_mutex', 30, '重点库', 7, 0, NOW(), NOW()),
(15, 'in_mutex', 31, '基础库', 8, 0, NOW(), NOW()),
-- 境外债 子集
(15, 'in_mutex', 24, '境外债一级库', 9, 0, NOW(), NOW()),
(15, 'in_mutex', 25, '境外债二级库', 10, 0, NOW(), NOW()),
(15, 'in_mutex', 26, '境外债三级库', 11, 0, NOW(), NOW()),
(15, 'in_mutex', 27, '境外债四级库', 12, 0, NOW(), NOW()),
(15, 'in_mutex', 28, '境外债五级库', 13, 0, NOW(), NOW()),
-- 债券产品库 子集
(15, 'in_mutex', 33, '稳富1号', 14, 0, NOW(), NOW()),
(15, 'in_mutex', 34, '嘉兴银行1号', 15, 0, NOW(), NOW()),
(15, 'in_mutex', 35, '稳富12号', 16, 0, NOW(), NOW()),
(15, 'in_mutex', 36, '稳富13号', 17, 0, NOW(), NOW()),
(15, 'in_mutex', 37, '稳富14号', 18, 0, NOW(), NOW()),
(15, 'in_mutex', 38, '稳富20号', 19, 0, NOW(), NOW()),
(15, 'in_mutex', 39, '稳富29号', 20, 0, NOW(), NOW()),
(15, 'in_mutex', 40, '稳富58号', 21, 0, NOW(), NOW()),
(15, 'in_mutex', 41, '兴金490号', 22, 0, NOW(), NOW()),
(15, 'in_mutex', 42, '兴锐5号', 23, 0, NOW(), NOW()),
(15, 'in_mutex', 43, '紫金1号1期', 24, 0, NOW(), NOW()),
(15, 'in_mutex', 44, '兴业京通', 25, 0, NOW(), NOW()),
(15, 'in_mutex', 45, '兴业太保大库', 26, 0, NOW(), NOW()),
(15, 'in_mutex', 46, '紫金1号2期', 27, 0, NOW(), NOW()),
(15, 'in_mutex', 47, '兴富101号', 28, 0, NOW(), NOW()),
(15, 'in_mutex', 48, '兴业京华债券大库', 29, 0, NOW(), NOW()),
(15, 'in_mutex', 49, '兴业稳盈', 30, 0, NOW(), NOW()),
(15, 'in_mutex', 50, '紫金1号3期', 31, 0, NOW(), NOW()),
(15, 'in_mutex', 51, '紫金1号4期', 32, 0, NOW(), NOW()),
(15, 'in_mutex', 52, '昆仑1号', 33, 0, NOW(), NOW()),
(15, 'in_mutex', 53, '兴业绿色信用债库', 34, 0, NOW(), NOW()),
(15, 'in_mutex', 54, '增利产业债认定', 35, 0, NOW(), NOW()),
(15, 'in_mutex', 55, '稳睿888号', 36, 0, NOW(), NOW()),
(15, 'in_mutex', 56, '稳睿8881号', 37, 0, NOW(), NOW()),
(15, 'in_mutex', 57, '兴富99号', 38, 0, NOW(), NOW()),
(15, 'in_linked', 17, '黑名单质押库', 1, 0, NOW(), NOW()),
(15, 'out_linked', 17, '黑名单质押库', 1, 0, NOW(), NOW()),
(23, 'in_linked', 17, '黑名单质押库', 1, 0, NOW(), NOW()),
(23, 'out_linked', 17, '黑名单质押库', 1, 0, NOW(), NOW()),
(99, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(100, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(101, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(102, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(103, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(104, 'in_restrict', 15, '债券禁止库', 1, 0, NOW(), NOW()),
(100, 'in_mutex', 101, '二级库', 1, 0, NOW(), NOW()),
(101, 'in_mutex', 100, '一级库', 1, 0, NOW(), NOW()),
(100, 'in_mutex', 102, '三级库', 2, 0, NOW(), NOW()),
(102, 'in_mutex', 100, '一级库', 2, 0, NOW(), NOW()),
(100, 'in_mutex', 103, '四级库', 3, 0, NOW(), NOW()),
(103, 'in_mutex', 100, '一级库', 3, 0, NOW(), NOW()),
(100, 'in_mutex', 104, '流通受限库', 4, 0, NOW(), NOW()),
(104, 'in_mutex', 100, '一级库', 4, 0, NOW(), NOW()),
(101, 'in_mutex', 102, '三级库', 5, 0, NOW(), NOW()),
(102, 'in_mutex', 101, '二级库', 5, 0, NOW(), NOW()),
(101, 'in_mutex', 103, '四级库', 6, 0, NOW(), NOW()),
(103, 'in_mutex', 101, '二级库', 6, 0, NOW(), NOW()),
(101, 'in_mutex', 104, '流通受限库', 7, 0, NOW(), NOW()),
(104, 'in_mutex', 101, '二级库', 7, 0, NOW(), NOW()),
(102, 'in_mutex', 103, '四级库', 8, 0, NOW(), NOW()),
(103, 'in_mutex', 102, '三级库', 8, 0, NOW(), NOW()),
(102, 'in_mutex', 104, '流通受限库', 9, 0, NOW(), NOW()),
(104, 'in_mutex', 102, '三级库', 9, 0, NOW(), NOW()),
(103, 'in_mutex', 104, '流通受限库', 10, 0, NOW(), NOW()),
(104, 'in_mutex', 103, '四级库', 10, 0, NOW(), NOW());

-- 自动调库定时任务绑定（rule_id = sys_scheduled_task.id，与 rrs_scheduled_task_demo_data 对齐）
INSERT INTO `ip_pool_auto_rule` (`id`, `pool_id`, `rule_type`, `rule_id`, `task_code`, `rule_desc`, `is_deleted`, `crte_time`, `updt_time`) VALUES
(1, 15, 'auto_out', 1, 'security_expired_auto_out', '到期证券自动出池', 0, NOW(), NOW()),
(2, 15, 'auto_in', 4, 'company_outer_rating_aa_minus_auto_in', '外评AA-及以下主体自动入池', 0, NOW(), NOW());

INSERT INTO `ip_pool_permission` (`pool_id`, `permission_type`, `handler_type`, `handler_id`, `handler_name`, `is_deleted`, `crte_time`, `updt_time`) VALUES
(1,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(2,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(3,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(4,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(5,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(6,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(7,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(8,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(15,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(16,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(17,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(18,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(23,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(24,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(25,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(26,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(27,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(28,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(29,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(30,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(31,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(32,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(33,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(34,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(35,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(36,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(37,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(38,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(39,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(40,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(41,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(42,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(43,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(44,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(45,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(46,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(47,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(48,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(49,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(50,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(51,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(52,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(53,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(54,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(55,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(56,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(57,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(58,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(59,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(60,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(61,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(62,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(63,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(64,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(65,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(66,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(67,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(68,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(69,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(70,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(71,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(72,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(73,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(74,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(75,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(76,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(77,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(78,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(79,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(80,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(81,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(82,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(83,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(84,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(85,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(86,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(87,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(88,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(89,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(90,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(91,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(92,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(93,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(94,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(95,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(96,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(97,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(98,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(99,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(100,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(101,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(102,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(103,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(104,  'viewable',         'user', 1, '管理员', 0, NOW(), NOW()),
(1,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(2,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(3,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(4,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(5,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(6,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(7,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(8,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(15,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(16,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(17,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(18,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(23,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(24,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(25,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(26,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(27,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(28,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(29,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(30,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(31,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(32,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(33,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(34,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(35,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(36,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(37,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(38,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(39,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(40,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(41,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(42,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(43,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(44,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(45,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(46,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(47,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(48,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(49,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(50,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(51,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(52,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(53,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(54,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(55,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(56,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(57,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(58,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(59,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(60,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(61,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(62,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(63,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(64,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(65,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(66,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(67,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(68,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(69,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(70,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(71,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(72,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(73,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(74,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(75,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(76,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(77,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(78,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(79,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(80,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(81,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(82,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(83,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(84,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(85,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(86,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(87,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(88,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(89,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(90,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(91,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(92,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(93,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(94,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(95,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(96,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(97,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(98,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(99,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(100,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(101,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(102,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(103,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(104,  'adjustable',       'user', 1, '管理员', 0, NOW(), NOW()),
(1,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(2,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(3,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(4,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(5,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(6,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(7,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(8,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(15,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(16,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(17,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(18,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(23,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(24,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(25,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(26,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(27,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(28,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(29,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(30,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(31,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(32,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(33,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(34,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(35,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(36,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(37,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(38,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(39,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(40,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(41,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(42,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(43,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(44,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(45,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(46,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(47,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(48,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(49,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(50,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(51,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(52,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(53,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(54,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(55,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(56,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(57,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(58,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(59,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(60,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(61,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(62,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(63,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(64,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(65,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(66,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(67,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(68,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(69,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(70,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(71,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(72,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(73,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(74,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(75,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(76,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(77,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(78,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(79,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(80,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(81,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(82,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(83,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(84,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(85,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(86,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(87,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(88,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(89,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(90,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(91,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(92,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(93,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(94,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(95,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(96,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(97,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(98,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(99,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(100,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(101,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(102,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(103,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(104,  'excel_importable',  'user', 1, '管理员', 0, NOW(), NOW()),
(2,  'adjustable',       'role', 2, '信用研究组', 0, NOW(), NOW()),
(3,  'adjustable',       'role', 2, '信用研究组', 0, NOW(), NOW()),
(4,  'adjustable',       'role', 2, '信用研究组', 0, NOW(), NOW()),
(5,  'adjustable',       'role', 2, '信用研究组', 0, NOW(), NOW()),
(6,  'adjustable',       'role', 2, '信用研究组', 0, NOW(), NOW()),
(15,  'adjustable',       'role', 2, '信用研究组', 0, NOW(), NOW()),
(59,  'adjustable',       'role', 2, '信用研究组', 0, NOW(), NOW()),
(60,  'adjustable',       'role', 2, '信用研究组', 0, NOW(), NOW()),
(61,  'adjustable',       'role', 2, '信用研究组', 0, NOW(), NOW()),
(62,  'adjustable',       'role', 2, '信用研究组', 0, NOW(), NOW()),
(63,  'adjustable',       'role', 2, '信用研究组', 0, NOW(), NOW()),
(100,  'adjustable',       'role', 2, '信用研究组', 0, NOW(), NOW()),
(101,  'adjustable',       'role', 2, '信用研究组', 0, NOW(), NOW()),
(102,  'adjustable',       'role', 2, '信用研究组', 0, NOW(), NOW()),
(103,  'adjustable',       'role', 2, '信用研究组', 0, NOW(), NOW()),
(104,  'adjustable',       'role', 2, '信用研究组', 0, NOW(), NOW()),
(24,  'adjustable',       'role', 3, '利率研究组', 0, NOW(), NOW()),
(25,  'adjustable',       'role', 3, '利率研究组', 0, NOW(), NOW()),
(26,  'adjustable',       'role', 3, '利率研究组', 0, NOW(), NOW()),
(27,  'adjustable',       'role', 3, '利率研究组', 0, NOW(), NOW()),
(28,  'adjustable',       'role', 3, '利率研究组', 0, NOW(), NOW()),
(2,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(3,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(24,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(25,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(18,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(64,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(33,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(34,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(35,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(36,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(37,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(38,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(39,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(40,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(41,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(42,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(43,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(44,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(45,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(46,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(47,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(48,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(49,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(50,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(51,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(52,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(53,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(54,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(55,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(56,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(57,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(67,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(68,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(69,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(70,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(71,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(72,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(74,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(75,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(76,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(77,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(78,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(79,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(80,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(81,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(82,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(83,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(84,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(85,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(87,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(88,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(89,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(90,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(91,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(92,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(93,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(94,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(95,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(96,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(97,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(98,  'adjustable',       'role', 4, '固收部', 0, NOW(), NOW()),
(29,  'adjustable',       'role', 7, '权益部', 0, NOW(), NOW()),
(30,  'adjustable',       'role', 7, '权益部', 0, NOW(), NOW()),
(31,  'adjustable',       'role', 7, '权益部', 0, NOW(), NOW()),
(1,  'viewable',         'role', 9, '量化部', 0, NOW(), NOW()),
(7,  'viewable',         'role', 9, '量化部', 0, NOW(), NOW()),
(8,  'viewable',         'role', 9, '量化部', 0, NOW(), NOW()),
(15,  'viewable',         'role', 9, '量化部', 0, NOW(), NOW()),
(16,  'viewable',         'role', 9, '量化部', 0, NOW(), NOW()),
(17,  'viewable',         'role', 9, '量化部', 0, NOW(), NOW()),
(18,  'viewable',         'role', 9, '量化部', 0, NOW(), NOW()),
(23,  'viewable',         'role', 9, '量化部', 0, NOW(), NOW()),
(32,  'viewable',         'role', 9, '量化部', 0, NOW(), NOW()),
(58,  'viewable',         'role', 9, '量化部', 0, NOW(), NOW()),
(64,  'viewable',         'role', 9, '量化部', 0, NOW(), NOW()),
(65,  'viewable',         'role', 9, '量化部', 0, NOW(), NOW()),
(86,  'viewable',         'role', 9, '量化部', 0, NOW(), NOW()),
(99,  'viewable',         'role', 9, '量化部', 0, NOW(), NOW()),
(15,  'adjustable',       'role', 10, '风险管理部', 0, NOW(), NOW()),
(16,  'adjustable',       'role', 10, '风险管理部', 0, NOW(), NOW()),
(17,  'adjustable',       'role', 10, '风险管理部', 0, NOW(), NOW()),
(23,  'adjustable',       'role', 10, '风险管理部', 0, NOW(), NOW()),
(64,  'adjustable',       'role', 10, '风险管理部', 0, NOW(), NOW()),
(1,  'viewable',         'role', 10, '风险管理部', 0, NOW(), NOW()),
(7,  'viewable',         'role', 10, '风险管理部', 0, NOW(), NOW()),
(8,  'viewable',         'role', 10, '风险管理部', 0, NOW(), NOW()),
(18,  'viewable',         'role', 10, '风险管理部', 0, NOW(), NOW()),
(32,  'viewable',         'role', 10, '风险管理部', 0, NOW(), NOW()),
(58,  'viewable',         'role', 10, '风险管理部', 0, NOW(), NOW()),
(65,  'viewable',         'role', 10, '风险管理部', 0, NOW(), NOW()),
(86,  'viewable',         'role', 10, '风险管理部', 0, NOW(), NOW()),
(99,  'viewable',         'role', 10, '风险管理部', 0, NOW(), NOW());

-- 开放日配置
TRUNCATE TABLE `ip_pool_open_day`;
INSERT INTO `ip_pool_open_day` (`id`, `pool_id`, `begin_date`, `end_date`, `description`, `is_deleted`, `crte_time`, `updt_time`) VALUES
(1, 8, '2026-01-01', '2026-06-30', '已过期开放区间（测试不在开放日校验）', 0, NOW(), NOW());
